complete -c rotbyte -l check -d 'Force re-hash of every file'
complete -c rotbyte -l report -d 'Print status report and exit'
complete -c rotbyte -l accept -r -F -d 'Accept a file as correct'
complete -c rotbyte -l accept-all -d 'Accept all current state as baseline'
complete -c rotbyte -l import -d 'Import .b2sum/.b2 hash files'
complete -c rotbyte -l workers -r -x -a '1 2 4 8 16' -d 'Parallel hashing workers'
complete -c rotbyte -s q -l quiet -d 'Only output problems'
complete -c rotbyte -l skip-missing -d 'Do not check for removed files'
complete -c rotbyte -l include-hidden -d 'Include hidden files and directories'
complete -c rotbyte -l exclude -r -x -a '(__fish_complete_directories)' -d 'Exclude directories'
complete -c rotbyte -l db -r -F -d 'Custom database path'
complete -c rotbyte -l version -d 'Show version'
complete -c rotbyte -l help -d 'Show help'