complete -c rotbyte -l check -d 'Force re-hash of every file'
complete -c rotbyte -l report -d 'Print status report and exit'
complete -c rotbyte -l accept -r -F -d 'Accept a file as correct'
complete -c rotbyte -l accept-all -d 'Accept all current state as baseline'
complete -c rotbyte -l import -d 'Import .b2sum/.b2 hash files'
complete -c rotbyte -l workers -r -x -a '1 2 4 8 16' -d 'Parallel hashing workers'
complete -c rotbyte -s q -l quiet -d 'Only output problems'
complete -c rotbyte -l skip-missing -d 'Do not check for removed files'
complete -c rotbyte -l include-hidden -d 'Include hidden files and directories'
complete -c rotbyte -l exclude -r -x -a '(__fish_complete_directories)' -d 'Exclude directories'
complete -c rotbyte -l db -r -F -d 'Custom database path'
complete -c rotbyte -l export -r -F -d 'Export checksums manifest'
complete -c rotbyte -l json -d 'Output results as JSON'
complete -c rotbyte -l budget -r -x -a '30m 1h 2h 4h 1h30m 2h30m' -d 'Time budget for full scans'
complete -c rotbyte -l due -r -x -a '7d 14d 30d 60d 90d' -d 'Re-verify files not checked within N days'
complete -c rotbyte -l track -d 'Install scheduled scans (launchd/systemd)'
complete -c rotbyte -l status -d 'Show status of all scheduled scans'
complete -c rotbyte -l untrack -d 'Remove scheduled scans for a directory'
complete -c rotbyte -l untrack-all -d 'Remove all scheduled scans'
complete -c rotbyte -l every -r -x -a '30m 1h 2h 4h' -d 'Quick scan frequency for --track'
complete -c rotbyte -l full-at -r -x -a '0h 1h 2h 3h 4h 6h 12h 14h 18h 22h' -d 'Daily clock times for full scans'
complete -c rotbyte -l notify -r -x -a 'email' -d 'Send notification on problems'
complete -c rotbyte -l notify-setup -r -x -a 'email' -d 'Interactive notification setup'
complete -c rotbyte -l version -d 'Show version'
complete -c rotbyte -l help -d 'Show help'